// loading
export const SHOW_LOADING =  "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// modal
export const SHOW_MODAL =  "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// socket
export const SET_USER_ID = "SET_USER_ID";
export const SEND_ADD_FRIEND_REQUEST = "SEND_ADD_FRIEND_REQUEST";
export const RECEIVED_ADD_FRIEND_REQUEST = "RECEIVED_ADD_FRIEND_REQUEST";
export const REMOVE_ADD_FRIEND_REQUEST = "REMOVE_ADD_FRIEND_REQUEST";
export const REMOVE_ADD_FRIEND_REQUEST_SUCCESS = "REMOVE_ADD_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_ADD_FRIEND_REQUEST = "ACCEPT_ADD_FRIEND_REQUEST";
export const ACCEPT_ADD_FRIEND_REQUEST_SUCCESS = "ACCEPT_ADD_FRIEND_REQUEST_SUCCESS";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_CONVERSATION = "GET_CONVERSATION";
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const SEND_NEW_CONVERSATION = "SEND_NEW_CONVERSATION";
export const NEW_CHAT = "NEW_CHAT";
export const GET_NEW_CHAT = "GET_NEW_CHAT";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const TYPING = "TYPING";
export const CLEAR_TYPING = "CLEAR_TYPING";
export const RECEIVE_CLEAR_TYPING = "RECEIVE_CLEAR_TYPING";
export const TYPING_MESSAGE = "TYPING_MESSAGE";
export const RECEIVE_MESSAGE_ASIDE = "RECEIVE_MESSAGE_ASIDE";
export const INSERT_MESSAGES = "INSERT_MESSAGES";

// user
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_REFRESH_TOKEN = "USER_REFRESH_TOKEN";
export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";
export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";
export const USER_CHANGE_AVATAR = "USER_CHANGE_AVATAR";

export const OK = 200;
export const CREATED = 201;
export const DELETED = 204;
export const BAD_REQUEST = 400;
export const UNAUTHORIZED = 401;
export const FORBIDDEN = 403;
export const NOT_FOUND = 404;
export const RECORD_EXIST = 406;
export const INVALID_PARAMETER = 422;
export const INTERNAL_SERVER = 500;
export const BAD_GATEWAY = 503;